"""Main context generation orchestrator."""

import os
from dataclasses import dataclass, field
from typing import Any, Callable, List, Optional

from repoview.config import (
    PRIORITY_ESSENTIAL,
    PRIORITY_FOCUS,
    TOKEN_BUDGET,
)
from repoview.core.collectors import collect_folder, collect_zip
from repoview.core.token_counter import count_tokens
from repoview.core.tree_builder import build_tree
from repoview.error_handler import error_handler, FileAccessError


@dataclass
class GenerateResult:
    """Result of context generation."""
    output_path: str
    total_tokens: int
    files_full: int = 0
    files_summary: int = 0
    files_metadata: int = 0
    files_omitted: int = 0
    warnings: List[str] = field(default_factory=list)
    all_entries: List[Any] = field(default_factory=list)
    files_structure_only: int = 0
    focus_path: str = ""


def _norm_focus(project_root: str, focus_path: str) -> str:
    """
    Normalise a user-supplied focus path to a relative POSIX path.
    
    Examples:
        focus_path = "src/auth"       → "src/auth/"
        focus_path = "./src/auth/"    → "src/auth/"
        focus_path = "src/auth.ts"    → "src/auth.ts"
        focus_path = "/abs/path/src"  → "src/"
    """
    if not focus_path:
        return ""

    root = os.path.abspath(project_root)
    fp = os.path.expanduser(focus_path)

    if os.path.isabs(fp):
        try:
            fp = os.path.relpath(fp, root)
        except ValueError:
            pass

    fp = fp.replace(os.sep, "/").lstrip("./").strip("/")

    if not fp:
        return ""

    abs_candidate = os.path.join(root, fp.replace("/", os.sep))
    if focus_path.rstrip().endswith("/") or (
        os.path.exists(abs_candidate) and os.path.isdir(abs_candidate)
    ):
        return fp + "/"

    return fp


@error_handler("generating context")
def generate_context(
    input_path: str,
    output_path: str,
    skip_docs: bool = False,
    skip_tests: bool = False,
    respect_gitignore: bool = True,
    token_budget: int = TOKEN_BUDGET,
    focus_path: str = "",
    progress_cb: Optional[Callable[[int, int], None]] = None,
) -> GenerateResult:
    """Generate LLM context file from a project."""
    
    # Collect files
    try:
        if os.path.isdir(input_path):
            entries = collect_folder(input_path, respect_gitignore)
            display = os.path.basename(os.path.abspath(input_path))
        elif input_path.lower().endswith(".zip"):
            entries = collect_zip(input_path)
            display = os.path.basename(input_path)
        else:
            raise FileAccessError(
                f"Unsupported input type: {input_path}",
                "Provide a folder path, ZIP file, or GitHub URL"
            )
    except OSError as e:
        raise FileAccessError(
            f"Cannot access input path: {input_path}",
            "Check that the path exists and you have read permissions"
        )

    if not entries:
        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write("(No files found)\n")
        except OSError as e:
            raise FileAccessError(
                f"Cannot write to output file: {output_path}",
                "Check that the directory exists and you have write permissions"
            )
        return GenerateResult(output_path, 0)

    # Process files
    total = len(entries)
    for i, e in enumerate(entries):
        e.process(skip_docs=skip_docs, skip_tests=skip_tests, focus_path=_norm_focus(input_path, focus_path))
        if progress_cb:
            progress_cb(i + 1, total)

    # Build header
    tree = build_tree(entries)
    _focus_norm = _norm_focus(input_path, focus_path)
    focus_note = f"\nFocus mode: {focus_path}  (all other files structure-only)" if focus_path else ""
    header = (
        f"repoview context — {display}{focus_note}\n"
        f"Generated by: repoview\n\n"
        f"Directory structure:\n{tree}\n\n"
        f"{'─'*60}\n\n"
    )
    used = count_tokens(header)

    # Filter content files
    content = [e for e in entries if not e.is_dir and e.initial_content_type != "structure_only"]
    structure_only_count = sum(1 for e in entries if not e.is_dir and e.initial_content_type == "structure_only")

    for e in content:
        if e.initial_content_type == "metadata":
            e.chosen = "metadata"
            e.tokens_chosen = e.tokens_summary
        else:
            e.chosen = "full"
            e.tokens_chosen = e.tokens_full
        used += count_tokens(f"── {e.relative_path} ──\n\n") + e.tokens_chosen

    # Trim pass 1: full → summary
    if used > token_budget:
        trimmable = sorted(
            [e for e in content
             if e.chosen == "full"
             and e.priority not in (PRIORITY_ESSENTIAL, PRIORITY_FOCUS)
             and e.tokens_summary < e.tokens_full],
            key=lambda e: (e.priority, -(e.tokens_full - e.tokens_summary)),
            reverse=True,
        )
        for e in trimmable:
            if used <= token_budget:
                break
            used -= e.tokens_full - e.tokens_summary
            e.chosen = "summary"
            e.tokens_chosen = e.tokens_summary

    # Trim pass 2: full/summary → omitted
    if used > token_budget:
        trimmable2 = sorted(
            [e for e in content
             if e.chosen in ("full", "summary")
             and e.priority not in (PRIORITY_ESSENTIAL, PRIORITY_FOCUS)],
            key=lambda e: (e.priority, -e.tokens_chosen),
            reverse=True,
        )
        for e in trimmable2:
            if used <= token_budget:
                break
            note_tokens = count_tokens(f"[Omitted: {e.relative_path}]")
            saving = e.tokens_chosen - note_tokens
            if saving > 0:
                used -= saving
                e.chosen = "omitted"
                e.tokens_chosen = note_tokens

    content.sort(key=lambda e: (e.priority, e.relative_path))

    # Write output file
    result = GenerateResult(
        output_path=output_path,
        total_tokens=0,
        files_structure_only=structure_only_count,
        focus_path=focus_path,
    )
    actual = count_tokens(header)

    try:
        with open(output_path, "w", encoding="utf-8") as out:
            out.write(header)
            for e in content:
                body = e.final_content()
                fh = (
                    f"── FILE: {e.relative_path} "
                    f"[{e.size}B | prio:{e.priority} | {e.chosen}] ──\n"
                )
                ff = f"\n── END: {e.relative_path} ──\n\n"
                actual += count_tokens(fh) + count_tokens(body) + count_tokens(ff)
                out.write(fh)
                out.write(body)
                out.write(ff)

                if e.chosen == "full":
                    result.files_full += 1
                elif e.chosen == "summary":
                    result.files_summary += 1
                elif e.chosen == "metadata":
                    result.files_metadata += 1
                else:
                    result.files_omitted += 1

            focus_footer = f"  focus: {focus_path}  structure-only: {structure_only_count}" if focus_path else ""
            footer = (
                f"\n{'─'*60}\n"
                f"repoview | tokens used: {actual:,} / {token_budget:,}\n"
                f"full: {result.files_full}  "
                f"summary: {result.files_summary}  "
                f"metadata: {result.files_metadata}  "
                f"omitted: {result.files_omitted}"
                f"{focus_footer}\n"
            )
            out.write(footer)
            actual += count_tokens(footer)
    except OSError as e:
        raise FileAccessError(
            f"Cannot write output file: {output_path}",
            "Check that you have write permissions and enough disk space"
        )

    if actual > token_budget * 1.05:
        result.warnings.append(
            f"Exceeded budget by {actual - token_budget:,} tokens. "
            f"Consider skipping more file types."
        )

    result.total_tokens = actual
    result.all_entries = entries

    # Save cache
    try:
        from repoview.cache import build_cache, save_cache
        settings = {
            "skip_docs": skip_docs,
            "skip_tests": skip_tests,
            "respect_gitignore": respect_gitignore,
            "focus_path": focus_path,
        }
        cache = build_cache(input_path, output_path, settings, entries)
        save_cache(cache)
    except Exception:
        pass

    return result
